const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),{app}=require('./app-harness.cjs');
function setup(c){vm.runInContext(`$('intakeDialog28').querySelectorAll=()=>['intakeParse28','intakeLocal29','intakeAdd29','intakeText28','intakeApply28'].map(id=>$(id));currentCase.mode='live';intake28={caseId:'room',commandId:'semantic',text:'淡水七人',items:[],plan:null};captureBase29(intake28);syncIntakeCaseFields29=()=>{};renderArrivalStatusCards=()=>{};`,c);}
test('辨識只產生草稿；修改中文九人後單筆確認更新共用資料',async()=>{const c=app();setup(c);vm.runInContext(`$('intakeText28').value='淡水分隊七人';`,c);await vm.runInContext('parseIntake28(true)',c);assert.equal(vm.runInContext('live.crews.length',c),0);assert.match(vm.runInContext("$('intakeChanges28').innerHTML",c),/data-field="number"/);assert.match(vm.runInContext("$('intakeChanges28').innerHTML",c),/data-commit/);vm.runInContext(`intake28.items[0].number='九';updateIntakeSummary29();`,c);assert.equal(vm.runInContext('intake28.plan.totalAfter',c),9);await vm.runInContext('applyIntakeRow30(intake28.items[0].id)',c);assert.equal(vm.runInContext('live.crews[0].count',c),9);assert.equal(vm.runInContext('live.intakeEvents[0].reviewedItems[0].number',c),'九');});
test('選入的模糊項目未確認不能送出；取消選入後清楚項目可先儲存並保存待辦',async()=>{const c=app();setup(c);vm.runInContext(`intake28.items=[FCIntake29.item('crew',{id:'a',unit:'淡水',number:7}),FCIntake29.item('support',{id:'b',task:'水庫車',text:'石台水庫車支援',uncertainty:'幾台？'})];renderIntakePlan28();$('intakeConfirm28').checked=true`,c);await assert.rejects(vm.runInContext('applyIntake28()',c),/未確認/);vm.runInContext(`intake28.items[1].selected=false;renderIntakePlan28();$('intakeConfirm28').checked=true`,c);await vm.runInContext('applyIntake28()',c);assert.equal(vm.runInContext('live.crews[0].count',c),7);assert.equal(vm.runInContext('live.intakeEvents[0].deferredItems.length',c),1);assert.equal(vm.runInContext('live.vehicles.length',c),0);});
test('純情資與指揮權變更可送出，復原同時還原SOP與紀錄',async()=>{const c=app();setup(c);vm.runInContext(`intake28.items=[FCIntake29.item('command',{id:'c',text:'已完成指揮權轉移'}),FCIntake29.item('note',{id:'n',text:'現場水源不足'})];renderIntakePlan28();$('intakeConfirm28').checked=true`,c);await vm.runInContext('applyIntake28()',c);assert.equal(vm.runInContext('currentCase.commandTransfer',c),true);assert.equal(vm.runInContext('currentCase.intakeNotes',c),'現場水源不足');await vm.runInContext("undoIntake28('semantic')",c);assert.equal(vm.runInContext('currentCase.commandTransfer',c),null);assert.equal(vm.runInContext('currentCase.intakeNotes',c),null);assert.equal(vm.runInContext('live.intakeEvents.length',c),2);});
test('同時有人修改SOP，舊草稿不能覆蓋；重新核對保留人工修正',async()=>{const c=app();setup(c);vm.runInContext(`intake28.items=[FCIntake29.item('note',{id:'n',text:'人工修正的情資'})];renderIntakePlan28();currentCase.intakeNotes='其他人的新回報';$('intakeConfirm28').checked=true`,c);await assert.rejects(vm.runInContext('applyIntake28()',c),/更新/);vm.runInContext(`captureBase29(intake28);renderIntakePlan28();$('intakeConfirm28').checked=true`,c);await vm.runInContext('applyIntake28()',c);assert.equal(vm.runInContext('currentCase.intakeNotes',c),'其他人的新回報\n人工修正的情資');});
test('晚到AI結果：切換案件或修改原文都不注入舊結果',async()=>{for(const action of ["currentCaseId='new-room';clearIntake28();", "$('intakeText28').value='竹圍六人';invalidateIntake28();"]){const c=app();setup(c);let finish;c.reply=()=>new Promise(resolve=>finish=resolve);vm.runInContext(`authenticatedAI=()=>reply();$('intakeText28').value='淡水七人'`,c);const pending=vm.runInContext('parseIntake28(false)',c);vm.runInContext(action,c);finish({ok:true,json:async()=>({draft:{correctedText:'淡水七人',items:[c.FCIntake29.item('crew',{unit:'淡水',number:7,evidence:'淡水七人'})]},providerUsed:'openai',modelUsed:'mock'})});await pending;assert.equal(vm.runInContext('live.crews.length',c),0);assert.equal(vm.runInContext('intake28?.plan||null',c),null);assert.equal(vm.runInContext("$('intakeParse28').disabled",c),false);}});
test('AI失敗保留原文且可使用本機，不假稱AI成功',async()=>{const c=app();setup(c);vm.runInContext(`authenticatedAI=async()=>({ok:false,json:async()=>({error:'AI額度不足'})});$('intakeText28').value='淡水七人'`,c);await assert.rejects(vm.runInContext('parseIntake28(false)',c),/額度/);assert.equal(vm.runInContext("$('intakeText28').value",c),'淡水七人');await vm.runInContext('parseIntake28(true)',c);assert.equal(vm.runInContext('intake28.meta.providerUsed',c),'local');assert.equal(vm.runInContext('intake28.plan.totalAfter',c),7);});
test('入口只在初期部署且預設收合；正式包完全移除自建收音',()=>{const html=fs.readFileSync(require.resolve('../index.html'),'utf8'),ui=fs.readFileSync(require.resolve('../assets/intake-ui.js'),'utf8'),app=fs.readFileSync(require.resolve('../assets/app.js'),'utf8');assert.equal(html.includes('id="openIntake28"'),false);assert.match(html,/<div class="arrival-detail-panel" data-arrival-panel="deployment" hidden>[\s\S]*?<details id="intakeDialog28" class="intake-panel29">/);assert.doesNotMatch(html+ui+app,/SpeechRecognition|webkitSpeechRecognition|getUserMedia|id="intakeMic28"|practiceResponseVoice/);assert.match(html,/手機鍵盤的語音轉文字/);assert.match(html,/intake-semantic\.js\?v=32/);});
test('編輯卡片真實oninput 與確認按鈕，不依賴勾選',async()=>{
 const c=app();setup(c);const number={tagName:'INPUT',dataset:{field:'number'},value:'七'},controls={};
 for(const name of ['[data-commit]','[data-edit-toggle]','[data-defer]','[data-remove]','[data-error]','.review-title30','.review-preview29','.review-state30','.review-editor30'])controls[name]={textContent:'',setAttribute(){},open:false};
 const card={dataset:{item:'edit'},querySelector(s){return controls[s]||null;},querySelectorAll(s){return s==='[data-field]'?[number]:[];}};c.card30=card;
 vm.runInContext(`$('intakeChanges28').querySelectorAll=s=>s==='[data-item]'?[card30]:[];intake28.items=[FCIntake29.item('crew',{id:'edit',unit:'淡水',number:7,uncertainty:'請核對人數'})];renderIntakePlan28();`,c);
 number.value='九';number.oninput();assert.equal(vm.runInContext('intake28.items[0].number',c),'九');assert.equal(vm.runInContext('live.crews.length',c),0);
 await controls['[data-commit]'].onclick();assert.equal(vm.runInContext('live.crews[0].count',c),9);
});
