const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),{app}=require('./app-harness.cjs');
function setup(c,text='淡水4人報到'){
 c.inputText=text;vm.runInContext(`
 const p28=FCIntake.plan(FCIntake.parse(inputText,FCIntake.roster(UNIT_TREE)),intakeSnapshot28(),{locate:intakePosition28,vehicleType});
 testEvent28={id:'command1',caseId:'room',kind:'apply',authorUid:'owner',raw:inputText,corrected:p28.corrected,writes:stampWrites28(p28.writes,'command1'),createdAt:Date.now(),summary:'測試登錄'};
 testRevision28=intakeRevision28();`,c);
}
function remote(c){
 const state=new Map([['cases/room',JSON.parse(vm.runInContext('JSON.stringify(currentCase)',c))]]);let fail=false,commits=0;
 const ref=path=>({path,id:path.split('/').at(-1),collection:n=>({doc:id=>ref(path+'/'+n+'/'+id)})});
 c.mockDB={collection:n=>({doc:id=>ref(n+'/'+id)}),async runTransaction(fn){const pending=[];const tx={async get(r){assert.equal(pending.length,0,'Firestore requires all reads before writes');return {exists:state.has(r.path),id:r.id,data:()=>structuredClone(state.get(r.path))};},set(r,data){pending.push(['set',r.path,structuredClone(data)]);},update(r,data){pending.push(['update',r.path,structuredClone(data)]);},delete(r){pending.push(['delete',r.path]);}};const result=await fn(tx);if(fail)throw Error('network-failed');for(const [kind,path,data]of pending){if(kind==='delete')state.delete(path);else if(kind==='update')state.set(path,{...state.get(path),...data});else state.set(path,data);}commits++;return result;}};
 vm.runInContext('db=mockDB;firebaseEnabled=true;',c);return {state,setFail:v=>fail=v,get commits(){return commits;}};
}
test('確認前不寫入；確認後在實戰与練習同樣更新人員與摘要',async()=>{for(const mode of ['live','practice']){const c=app();c.mode=mode;vm.runInContext('currentCase.mode=mode;',c);setup(c);assert.equal(vm.runInContext('live.crews.length',c),0);await vm.runInContext('commitIntake28(testEvent28,testRevision28)',c);assert.equal(vm.runInContext('live.crews[0].count',c),4);assert.equal(vm.runInContext('currentCase.crews[0].count',c),4);assert.match(vm.runInContext('effectiveDeploymentSummary()',c),/4人/);assert.equal(vm.runInContext('live.logs[0].message',c),'測試登錄');}});
test('UI 確認核取未勾選，不可套用；完成後可接第二次回報',async()=>{const c=app();setup(c);vm.runInContext(`intake28={caseId:'room',commandId:'ui',text:inputText,choices:{},plan:p28,revision:testRevision28};$('intakeConfirm28').checked=false`,c);await assert.rejects(vm.runInContext('applyIntake28()',c),/勾選/);vm.runInContext("$('intakeConfirm28').checked=true",c);await vm.runInContext('applyIntake28()',c);assert.equal(vm.runInContext('live.crews[0].count',c),4);assert.equal(vm.runInContext('intake28.plan===null&&intake28.text===\'\'',c),true);});
test('本機持久化失敗：不留半套人數、圖面或成功紀錄',async()=>{const c=app();setup(c);c.localStorage.setItem=()=>{throw Error('quota');};await assert.rejects(vm.runInContext('commitIntake28(testEvent28,testRevision28)',c),/quota/);assert.equal(vm.runInContext('live.crews.length',c),0);assert.equal(vm.runInContext('(live.intakeEvents||[]).length',c),0);});
test('遠端交易：同一命令重送只增加一次，回報與日誌原子提交',async()=>{const c=app();setup(c);const r=remote(c);await vm.runInContext('commitIntake28(testEvent28,testRevision28)',c);const result=await vm.runInContext('commitIntake28(testEvent28,testRevision28)',c);assert.equal(result.duplicate,true);assert.equal(r.state.get('cases/room').resourceRevision,1);assert.equal([...r.state.keys()].filter(p=>p.includes('/crews/')).length,1);assert.ok(r.state.has('cases/room/intakeEvents/command1'));assert.equal(r.state.get('cases/room/logs/command1').message,'測試登錄');});
test('遠端交易：提交失敗沒有任何部分寫入',async()=>{const c=app();setup(c);const r=remote(c);r.setFail(true);await assert.rejects(vm.runInContext('commitIntake28(testEvent28,testRevision28)',c),/network/);assert.equal(r.state.size,1);});
test('遠端交易：手動新增／旋轉後的舊預覽被拒絕',async()=>{const c=app();setup(c);const r=remote(c);r.state.get('cases/room').resourceRevision=1;await assert.rejects(vm.runInContext('commitIntake28(testEvent28,testRevision28)',c),/更新/);assert.equal(r.state.size,1);});
test('遠端交易：即使舊客戶端未推進版本，已修改的同筆資料仍不可覆蓋',async()=>{const c=app();vm.runInContext("live.crews=[{id:'old',unit:'淡水',count:4}]",c);setup(c,'淡水修正為6人');const r=remote(c);r.state.set('cases/room/crews/old',{unit:'淡水',count:5});await assert.rejects(vm.runInContext('commitIntake28(testEvent28,testRevision28)',c),/更新/);assert.equal(r.state.get('cases/room/crews/old').count,5);});
test('案件已切換或已關閉時拒絕遲來的回報',async()=>{const c=app();setup(c);vm.runInContext("currentCaseId='other'",c);await assert.rejects(vm.runInContext('commitIntake28(testEvent28,testRevision28)',c),/切換|變更/);vm.runInContext("currentCaseId='room'",c);const r=remote(c);r.state.get('cases/room').status='closed';await assert.rejects(vm.runInContext('commitIntake28(testEvent28,testRevision28)',c),/結束/);});
test('復原保留審計；有後續修改時拒絕破壞新資料',async()=>{const c=app();setup(c);await vm.runInContext('commitIntake28(testEvent28,testRevision28)',c);vm.runInContext("intake28={caseId:'room',plan:null};live.crews[0].count=6;",c);await assert.rejects(vm.runInContext("undoIntake28('command1')",c),/更新/);vm.runInContext('live.crews[0].count=4;',c);await vm.runInContext("undoIntake28('command1')",c);assert.equal(vm.runInContext('live.crews.length',c),0);assert.equal(vm.runInContext('live.intakeEvents.length',c),2);assert.equal(vm.runInContext('live.intakeEvents[1].undoOf',c),'command1');});
test('舊文字保留但不再蓋過最新人數摘要',async()=>{const c=app();vm.runInContext("currentCase.deploymentTextRecord='淡水2人第一面';$('deploymentTextRecord').value='淡水2人第一面'",c);setup(c);await vm.runInContext('commitIntake28(testEvent28,testRevision28)',c);assert.equal(vm.runInContext('currentCase.deploymentTextRecord',c),'淡水2人第一面');assert.match(vm.runInContext('effectiveDeploymentSummary()',c),/4人/);});
test('v29 遠端交易：同時提交人員與SOP差異；SOP過期時整筆拒絕',async()=>{const c=app();setup(c);vm.runInContext("testEvent28.caseChanges=[{key:'supportState',before:null,after:'needed'}];",c);const r=remote(c);r.state.get('cases/room').supportState='none';await assert.rejects(vm.runInContext('commitIntake28(testEvent28,testRevision28)',c),/SOP/);assert.equal(r.state.size,1);delete r.state.get('cases/room').supportState;await vm.runInContext('commitIntake28(testEvent28,testRevision28)',c);assert.equal(r.state.get('cases/room').supportState,'needed');assert.equal([...r.state.keys()].filter(x=>x.includes('/crews/')).length,1);assert.equal(r.state.get('cases/room/intakeEvents/command1').caseChanges.length,1);});
