const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const {app}=require('./app-harness.cjs');
test('整合：房主自我練習不是教官，另一角色回報不會替主受測者跳關',async()=>{const c=app();assert.equal(vm.runInContext('isHumanInstructor()',c),false);await vm.runInContext('togglePracticeRun()',c);assert.equal(vm.runInContext('currentCase.training.phase',c),'running');vm.runInContext("live.practiceResponses.push({id:'other',eventId:'a',authorUid:'another',role:'安全官',text:'已回報危害資訊',createdAt:Date.now()})",c);await vm.runInContext('processTraining()',c);assert.equal(vm.runInContext('currentCase.training.index',c),0);vm.runInContext("live.practiceResponses.push({id:'owner-r',eventId:'a',authorUid:'owner',role:'現場指揮官',text:'指揮點建立並已完成初報',createdAt:Date.now()})",c);await vm.runInContext('processTraining()',c);assert.equal(vm.runInContext('currentCase.training.index',c),1);assert.ok(vm.runInContext('live.practiceMessages.length>0',c));});
test('整合：真人教官可開始與結束；受測者無法呼叫教官推進',async()=>{const c=app();vm.runInContext("currentCase.instructorMode='human';currentCase.instructorUid='owner'",c);assert.equal(vm.runInContext('myTrainingRole()',c),'教官');await vm.runInContext('togglePracticeRun()',c);vm.runInContext("profile.id='trainee'",c);await vm.runInContext('releaseNextPracticeEvent()',c);assert.equal(vm.runInContext('currentCase.training.index',c),0);vm.runInContext("profile.id='owner'",c);await vm.runInContext("trainingCommit({type:'finish'})",c);assert.equal(vm.runInContext('currentCase.training.phase',c),'completed');});
test('整合：確認回報一次更新人車水線，旋轉後保留連結',async()=>{const c=app();await vm.runInContext(`
const parsed=FCIntake.parse('淡水61供水給淡水11；淡水11第一面出兩線；竹圍4人第三面搜救',FCIntake.roster(UNIT_TREE));
const plan=FCIntake.plan(parsed,intakeSnapshot28(),{locate:intakePosition28,vehicleType});
const event={id:'one',caseId:'room',kind:'apply',authorUid:'owner',raw:'測試',corrected:'測試',writes:stampWrites28(plan.writes,'one'),createdAt:Date.now(),summary:'回報'};
commitIntake28(event,intakeRevision28());`,c);assert.equal(vm.runInContext('live.vehicles.length',c),2);assert.equal(vm.runInContext('live.hoses.length',c),3);const before=vm.runInContext('JSON.stringify(live.hoses)',c),lat=vm.runInContext('live.crews[0].lat',c);await vm.runInContext("saveBuildingBox({rotationDeg:90})",c);assert.equal(vm.runInContext('JSON.stringify(live.hoses)',c),before);assert.notEqual(vm.runInContext('live.crews[0].lat',c),lat);assert.equal(vm.runInContext('currentCase.buildingBox.rotationDeg',c),90);});
test('整合：SDS 保存須有核對與原文來源',async()=>{const c=app();await assert.rejects(vm.runInContext('saveSds27()',c),/核對/);vm.runInContext("$('sdsConfirmed27').checked=true;$('sdsProduct27').value='測試產品'",c);await assert.rejects(vm.runInContext('saveSds27()',c),/原檔或原文連結/);vm.runInContext("$('sdsUrl27').value='javascript:alert(1)'",c);await assert.rejects(vm.runInContext('saveSds27()',c),/HTTPS/);});
test('整合：初期指揮官受測時，不加入競爭指揮權的 AI 現場指揮官',async()=>{const c=app();vm.runInContext("live.players[0].role='初期指揮官'",c);await vm.runInContext('fillPracticeAiRoles(true)',c);assert.equal(vm.runInContext("live.players.some(p=>p.ai&&p.role==='現場指揮官')",c),false);});

