const {test}=require('node:test'),A=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const S=require('../assets/scene32'),T=require('../assets/tactics31');
const c={lat:25,lng:121,buildingBox:{lat:25,lng:121,widthM:40,heightM:28,rotationDeg:0}};
const vehicle=(id,face='第一面')=>({id,unit:'淡水',name:'淡水'+id,type:'水車',face,task:'攻擊車',...T.point(c.buildingBox,face,'vehicle',0)});
const hose=(id,unit='淡水')=>({id,vehicleId:'11',unit,targetType:'buildingFace',targetName:'第一面',lineNo:id});
test('同一車不同分隊2至6線都有獨立車頭出水點及入口',()=>{for(let n=2;n<=6;n++){const s=S.build(c,{vehicles:[vehicle('11')],hoses:Array.from({length:n},(_,i)=>hose(''+i,i%2?'竹圍':'淡水'))});A.equal(s.lines.length,n);A.equal(new Set(s.lines.map(h=>JSON.stringify(h.path[0]))).size,n);A.equal(new Set(s.lines.map(h=>JSON.stringify(h.path[2]))).size,n);for(const h of s.lines)A.equal(h.sourceId,'11');}});
test('車號和分隊名稱不重複',()=>{A.equal(S.crewName({unit:'竹圍',leader:'竹圍'}),'竹圍');A.equal(S.build(c,{vehicles:[{...vehicle('11'),name:'11'}]}).nodes[0].label,'淡水11');});
test('離群火點不縮小火場，顯示遠處資料可取回',()=>{const state={hazards:[{id:'far',type:'起火點',lat:25.1,lng:121.1}]},s=S.build(c,state);A.equal(s.far.length,1);A.equal(s.nodes.length,0);A.equal(S.build(c,state,{all:true}).nodes.length,1);A.ok(s.W<2000);});
test('建物與10m比例尺沿兩軸使用相同比例',()=>{const s=S.build(c,{}),svg=S.svg(s);A.ok(svg.includes('h60'));A.ok(Math.abs((s.corners[1].x-s.corners[0].x)*s.scale-240)<.01);A.equal(s.box.heightM*s.scale,168);});
test('已進入的人員在建物內，撤出優先於舊interior欄位',()=>{const crews=[{id:'a',unit:'淡水',face:'第一面',status:'作業中',task:'已進入',floor:'3樓'},{id:'b',unit:'竹圍',interior:true,status:'撤出',task:'內攻'}];const s=S.build(c,{crews});A.equal(s.nodes[0].inside,true);A.ok(Math.abs(s.nodes[0].x)<20&&Math.abs(s.nodes[0].y)<14);A.match(s.nodes[0].detail,/3樓/);A.equal(s.nodes[1].inside,false);});
test('SOP及回報明確位置產生指揮站及前進指揮所，預定不當既成',()=>{const s=S.build({...c,firstSideNote:'第一面',intakeNotes:'第三面成立前進指揮所。預計第二面成立救護車集結區'},{});A.ok(s.nodes.some(n=>n.label==='指揮站'));A.ok(s.nodes.some(n=>n.label==='前進指揮所'));A.ok(!s.nodes.some(n=>n.label==='救護車集結區'));});
test('各面頭車獨立，無唯一來源時不任意接線',()=>{const s=S.build(c,{vehicles:[vehicle('11'),vehicle('16','第二面')],hoses:[{...hose('a'),vehicleId:'',targetName:'第二面'}]});A.equal(s.lines[0].sourceId,'16');const missing=S.build(c,{vehicles:[],hoses:[hose('a')]});A.equal(missing.lines.length,0);A.ok(missing.notes.some(n=>n.includes('待確認')));});
test('道路排列依折線且手動車輛保留位置',()=>{const points=[S.ll(c.buildingBox,{x:30,y:-25}),S.ll(c.buildingBox,{x:70,y:-25})];const s=S.build({...c,deploymentRoads32:{第一面:{points}}},{vehicles:[vehicle('11'),{...vehicle('16'),task:'供水',queueOrder:1},{...vehicle('61'),task:'供水',positionManual:true,lat:25.001,lng:121.001}]});A.ok(Math.abs(s.nodes[0].x-30)<.01);A.ok(Math.abs(s.nodes[1].x-42)<.01);A.ok(s.nodes[2].x>90);A.equal(s.nodes[0].heading,270);});
test('共享UI安裝與道路交易保留資料版本',async()=>{const {app}=require('./app-harness.cjs'),ctx=app();vm.runInContext(fs.readFileSync(require.resolve('../assets/scene-ui32.js'),'utf8'),ctx);vm.runInContext(`installScene32();currentCase.buildingBox=${JSON.stringify(c.buildingBox)};live.vehicles=${JSON.stringify([vehicle('11')])};roadDraft32={caseId:currentCaseId,face:'第一面',points:[{lat:24.9998,lng:121.0003},{lat:24.9998,lng:121.002}],source:'manual'};renderLiveParts=()=>{};`,ctx);await vm.runInContext('applyRoad32()',ctx);A.equal(vm.runInContext('live.intakeEvents.length',ctx),1);A.equal(vm.runInContext('currentCase.deploymentRoads32["第一面"].source',ctx),'manual');A.equal(vm.runInContext('live.vehicles[0].lastIntakeId===live.intakeEvents[0].id',ctx),true);A.equal(vm.runInContext('deploymentSchematicHtml===deploymentSchematic32&&renderMap===renderGoogle32',ctx),true);});

test('手動指揮站帶動未指派人員待命位置',()=>{const command=S.ll(c.buildingBox,{x:-60,y:-35}),s=S.build(c,{hazards:[{id:'cmd',type:'指揮站',...command}],crews:[{id:'c',unit:'三芝',status:'待命'}]});const crew=s.nodes.find(n=>n.id==='c');A.ok(Math.abs(crew.x+60)<.01&&Math.abs(crew.y+50)<.01);});
